- setenv.sh
- start_torq_demo.sh
- start_torq_demo_osx.sh
- stop_torq_demo.sh
Moved KDBBASEPORT assignment into setenv.sh
> Moved KDBBASEPORT assignment into setenv.sh

- appconfig/settings/monitor.q
- appconfig/settings/rdb.q
- appconfig/settings/sort.q
- appconfig/settings/sortslave.q
- appconfig/settings/wdb.q
Removed some unnecessary connections
> Rationalised connections

- start_torq_demo.sh
Added nohup to keep processes alive, other TorQ packages seem to have this included.
> Added nohup to bash start script

- README.md
Reorder release notes in README to read newest first.
> Sort README descending

- appconfig/process.csv
- docs/gettingstarted.md
- start_torq_demo.bat
- start_torq_demo.sh
- start_torq_demo_osx.sh
Timeout command line argument (-T) changed to 180 seconds in startup scripts and documentation.
> RDB timeout

- README.md
- appconfig/settings/iexfeed.q
- code/iexfeed/iex.q
- setenv.sh
This pull request will modify the API link used to connect to IEX cloud as the url and authentication have changed. Also, because the API updated, an API token is required to access the data, which is added to the environment variable where it should be stated in the documentation that the user should create their own.
> Iex Feed Issue

- setenv.sh
Fixed mistake from previous merge.
> Fixed mistake on variable name

- appconfig/process.csv
- setenv.sh
Aimed to address the issue of TP logs and HDB data stored in the same directory. now TP logs will be saved in /tplogs and hdb saved in /hdb
> Store TP logs and HDB in separate locations

- code/tick/feed.q
- database.q
Add a `side` column to the the `trade` table
```
:7202>trade
time                          sym  price size stop cond ex side
---------------------------------------------------------------
2019.11.19D12:08:16.998769000 MSFT 28.99 43   1    Z    N  buy
2019.11.19D12:08:17.199773000 HPQ  36    43   0    8    O  buy
2019.11.19D12:08:17.199773000 MSFT 29.04 8    0    B    N  sell
2019.11.19D12:08:17.199773000 MSFT 29.04 47   0    L    N  buy
2019.11.19D12:08:17.199773000 HPQ  36.03 22   0    P    O  buy
```
> Add side to trade table

- appconfig/monitorconfig.csv
- setenv.sh
Add port number for data dog process, and default configuration for monitor process.
> Add data dog config

- appconfig/dqcconfig.csv
Running on the trade and quote table in rdb1
> Adding a sample line to dqc config file for function refdatacheck

- appconfig/dqcconfig.csv
- appconfig/dqedetail.csv
We have renamed anomalychk to infinitychk in TorQ, so we need to change their names in the config files.
> Change anomalychk to infinitychk in config

- README.md
- appconfig/application.txt
- appconfig/dependency.csv
Increase version number from 1.6.0 to 1.8.0 (we missed 1.7.0) and TorQ dependency from 2.7.0 to 3.7.0.
> Change version number

- appconfig/settings/segmentedtickerplant.q
> Change autobatch mode name to memorybatch in STP

- appconfig/housekeeping.csv
Adds scheduling to housekeeping for creating .tar.gz files from segmented tickerplant daily logs.
Corresponds with PR #319 on [TorQ](https://github.com/AquaQAnalytics/TorQ/pull/319)
> Housekeeping stp

- README.md
- appconfig/application.txt
Releaseing TorQ-FSP to v 1.9.0
> Creating a release

- README.md
- appconfig/application.txt
Release request to have the installlatest.sh in the new version.
> Release v1.9.1

- README.md
- appconfig/application.txt
- appconfig/dependency.csv
version number has been bumped
version for TorQ dependency updated
> version number updates for new release

- installlatest.sh
any possible character naming convention for github tag names works with install script
> install script now allows for all tag naming conventions

- appconfig/dqcconfig.csv
updating exmaple of dqc config csv, as dqc allow multiple processes in one line, and expands it to multiple in configtable now
> updating exmaple of dqc config csv

- appconfig/settings/filealerter.q
Update .fa.tickerplanttype variable to use segmented tp as default an use this variable in .server.CONNECTIONS
> update default tp to segmentedtp

- appconfig/passwords/accesslist.txt
- appconfig/settings/tailer.q
- appconfig/torqv5process.csv
Added tailer process to appconfig
> updated appconfig to include tailerprocess

- appconfig/torqv5process.csv
Adds main EOD process to torq5 process file to start process with stack.
> TCS-100 Add EOD process to torq5process.csv

- appconfig/settings/default.q
- appconfig/striping.json
Updated numseg to a default of 1, removed second variable from .ds.stripe function
> TCS-115 Update FSP defaults and striping.json

- appconfig/striping.json
Add the skey as a parameter back into the call of .ds.stripe within the json
> TCS-162 Add skey back into json

- appconfig/torqv5process.csv
Fixing conflicts/errors after merging code together into torq5_develop.
> TorQ Cloud post merge fixes to torqv5process.csv

- docs/index.md
Changed occurrences of "support@dataintellect.com" to "torqsupport@dataintellect.com" across the repo.
Modification to documentation
-  I have performed a self-review of my code
-  My changes generate no new warnings
> Change support email address in repo

- appconfig/passwords/accesslist.txt
The access list was not updated when idb was created, need to add this now
> Update accesslist.txt with ldb:pass
